"""empty message

Revision ID: 758209ab6de2
Revises: 1039b8d78f9c
Create Date: 2024-11-20 16:40:17.408070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758209ab6de2'
down_revision = '1039b8d78f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
